#Web服务器相关配置
server:
  port: 8092
  servlet:
    context-path:

  #数据连接配置
spring:
  profiles:
    active:
  application:
    name: TIBMAS2-WEBAPI_LOCAL
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/tibmas?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initial-size: 5
      maxActive: 10
      minIdle:  10
      validation-query: SELECT 'x' from dual
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      useGlobalDataSourceStat: true
      # 支持火星文emoji表情
      connectionInitSqls: set names utf8mb4;
      # 确保链接可用
      keep-alive: true
  #mongodb配置
  data:
    elasticsearch:
      cluster-name: lzw-elasticsearch
      cluster-nodes: 120.76.174.43:9500,120.76.174.43:9700,120.76.174.43:9900