#Web服务器相关配置
server:
  port: 11142
  servlet:
    context-path: /tibmas2-webapi

  #数据连接配置
spring:
  profiles:
    active:
  application:
    name: TIBMAS2-WEBAPI_LOCAL
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/tibmas?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initial-size: 5
      maxActive: 10
      minIdle:  10
      validation-query: SELECT 'x' from dual
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      useGlobalDataSourceStat: true
      # 支持火星文emoji表情
      connectionInitSqls: set names utf8mb4;
      # 确保链接可用
      keep-alive: true

  #Redis连接
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 11
        maxIdle: 11
        maxWait: -1
        minIdle: 0


  #json格式化
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  #session共享
  session:
    store-type: redis

  #文件上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  #kafka
  kafka:
    bootstrap-servers: 172.16.8.19:9092
    consumer:
      group-id: TIBMAS_WEBAPI_GROUP_${random.uuid}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      client-id: TIBMAS_WEBAPI_CLIENT_${random.uuid}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #mybatis
mybatis:
  configurationm:
    apUnderscoreToCamelCase: true
    jdbcTypeForNull: NULL

#日志
logging:
  level:
    com.lzw: DEBUG
    org: INFO


  #分布助手配置
  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql


  #注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic

  #kafka队列
wind:
  tibmas:
    info2kafka:
      enabled: true

#添加 分布式事物
## tx-manager 配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070